### ISSUE TITLE
Error with help command 

### ISSUE THREAD

**Issue by teorailin** [Cramenorn/RaptorSA#21]
Console log:
/home/teorailin/Escritorio/RaptorSA/node_modules/discord.js/src/structures/MessageEmbed.js:443
      .flat(2)
       ^

TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/teorailin/Escritorio/RaptorSA/node_modules/discord.js/src/structures/MessageEmbed.js:443:8)
    at MessageEmbed.addFields (/home/teorailin/Escritorio/RaptorSA/node_modules/discord.js/src/structures/MessageEmbed.js:259:42)
    at MessageEmbed.addField (/home/teorailin/Escritorio/RaptorSA/node_modules/discord.js/src/structures/MessageEmbed.js:250:17)
    at Object.exports.run (/home/teorailin/Escritorio/RaptorSA/src/commands/info/help.js:10:14)
    at module.exports (/home/teorailin/Escritorio/RaptorSA/src/events/message.js:30:13)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/home/teorailin/Escritorio/RaptorSA/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/teorailin/Escritorio/RaptorSA/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/teorailin/Escritorio/RaptorSA/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/home/teorailin/Escritorio/RaptorSA/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)

this is when u execute help command

**Comment by MalwareWerewolf** [comment]
Hi @teorailin ,
there is already an issue opened on the [Discord.js repository](https://github.com/discordjs/discord.js/issues/3910), try to update node.js
